#! /usr/bin/env bash

if [ ! -z "$(git status --porcelain)" ]; then
  echo 'the repo is unclean, bailing out'
  exit 1
fi

if [ 'main' != "$(git branch --show-current)" ]; then
  echo 'not on main, bailing out'
  exit 1
fi

while read -r branch; do
  if [ 'gh-pages' == "${branch}" ]; then
    echo 'gh-pages branch exists locally, bailing out'
    exit 1
  fi
done < <(git branch --format='%(refname:short)')


if [ -z "$(git ls-remote origin gh-pages)" ]; then
  echo 'remote gh-pages branch does not exist, bailing out'
  exit 1
fi

git fetch origin
git switch gh-pages
git merge --no-edit origin/main || exit 1

for DIR in $(find ./gh-pages -type d); do
  (
    echo "<html>\n<body>\n<h1>Toofab Schemas</h1>\n<hr/>\n<pre>"
    ls -1pa "${DIR}" | egrep "(../|json)" | grep -v "^\./$" | grep -v "index.html" | awk '{ printf "<a href=\"%s\">%s</a>\n",$1,$1 }'
    echo "</pre>\n</body>\n</html>"
  ) > "${DIR}/index.html"
done

git add -A
git commit -m "Updated gh-pages directory listing"
git push origin gh-pages
git checkout main
git branch -D gh-pages